// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgaUyfJ2fTjCmikfGABcI_reQholajGD8',
    appId: '1:1084671688009:web:03c5848818f3100e4f2e98',
    messagingSenderId: '1084671688009',
    projectId: 'foodify-app-23dda',
    authDomain: 'foodify-app-23dda.firebaseapp.com',
    storageBucket: 'foodify-app-23dda.firebasestorage.app',
    measurementId: 'G-JQF9M5YWS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4SWLH3J_gQgqZerxNCz8dFAweTTprR_4',
    appId: '1:1084671688009:android:2f78b65b833e238c4f2e98',
    messagingSenderId: '1084671688009',
    projectId: 'foodify-app-23dda',
    storageBucket: 'foodify-app-23dda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSiYjaoue0qHZemjJD1ftLkWMjP1w7v84',
    appId: '1:1084671688009:ios:ca74752ecbe564974f2e98',
    messagingSenderId: '1084671688009',
    projectId: 'foodify-app-23dda',
    storageBucket: 'foodify-app-23dda.firebasestorage.app',
    iosBundleId: 'com.emre.foodifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSiYjaoue0qHZemjJD1ftLkWMjP1w7v84',
    appId: '1:1084671688009:ios:ca74752ecbe564974f2e98',
    messagingSenderId: '1084671688009',
    projectId: 'foodify-app-23dda',
    storageBucket: 'foodify-app-23dda.firebasestorage.app',
    iosBundleId: 'com.emre.foodifyApp',
  );
}
